from snakemake.utils import validate


configfile: "config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


include: "rules/common.smk"
include: "rules/genecart.smk"


rule all:
    input:
        "results/genecart/association_rules.tsv",
